In [1]:
sentence="The quick brown fox jumps over the lazy dog"

In [5]:
words=sentence.split()

In [7]:
words

['The', 'quick', 'brown', 'fox', 'jumps', 'over', 'the', 'lazy', 'dog']

In [8]:
unique_words=set(words)

In [9]:
unique_words

{'The', 'brown', 'dog', 'fox', 'jumps', 'lazy', 'over', 'quick', 'the'}

In [10]:
encoding={}

In [20]:
for i,word in enumerate(unique_words):
    print(word)
    print(i)
    encoding[word]=[0]*i+[1]+[0]*(len(unique_words))

The
0
the
1
dog
2
brown
3
fox
4
quick
5
lazy
6
over
7
jumps
8


In [17]:
for word in words:
    print(word,encoding[word])

The [1, 0, 0, 0, 0, 0, 0, 0, 0, 0]
quick [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0]
brown [0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0]
fox [0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0]
jumps [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0]
over [0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0]
the [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0]
lazy [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0]
dog [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0]


In [4]:
import numpy as np
import tensorflow as tf
from tensorflow import keras


In [5]:
from keras.datasets import imdb

In [6]:
(X_train,y_train), (X_test, y_test) = imdb.load_data(num_words=1000)

In [7]:
def vectorize_sequences(sequences,dimension=10000):
    results=np.zeros((len(sequences),dimension))
    for i,sequence in enumerate(sequences):
      results[i,sequence]=1
    return results

In [8]:
x_train=vectorize_sequences(X_train)
x_test=vectorize_sequences(X_test)


In [9]:
y_train=np.asarray(y_train).astype('float32')
y_test=np.asarray(y_test).astype('float32')

In [10]:
x_train

array([[0., 1., 1., ..., 0., 0., 0.],
       [0., 1., 1., ..., 0., 0., 0.],
       [0., 1., 1., ..., 0., 0., 0.],
       ...,
       [0., 1., 1., ..., 0., 0., 0.],
       [0., 1., 1., ..., 0., 0., 0.],
       [0., 1., 1., ..., 0., 0., 0.]])

In [11]:
x_test

array([[0., 1., 1., ..., 0., 0., 0.],
       [0., 1., 1., ..., 0., 0., 0.],
       [0., 1., 1., ..., 0., 0., 0.],
       ...,
       [0., 1., 1., ..., 0., 0., 0.],
       [0., 1., 1., ..., 0., 0., 0.],
       [0., 1., 1., ..., 0., 0., 0.]])

In [12]:
y_train

array([1., 0., 0., ..., 0., 1., 0.], dtype=float32)

In [13]:
y_test

array([0., 1., 1., ..., 0., 0., 0.], dtype=float32)

In [17]:
embedding_dim=16
model=keras.Sequential([keras.layers.Embedding(10000,embedding_dim,input_length=10000),
keras.layers.Flatten(),
keras.layers.Dense(16,activation='relu'),
keras.layers.Dense(1,activation='sigmoid')])

In [18]:
model.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

In [19]:
history=model.fit(x_train,y_train,epochs=5,batch_size=512,validation_data=(x_test,y_test))

Epoch 1/5
49/49 [==============================] - 80s 1s/step - loss: 0.7937 - accuracy: 0.5502 - val_loss: 0.6536 - val_accuracy: 0.5332
Epoch 2/5
49/49 [==============================] - 58s 1s/step - loss: 0.5672 - accuracy: 0.7613 - val_loss: 0.4923 - val_accuracy: 0.7994
Epoch 3/5
49/49 [==============================] - 207s 4s/step - loss: 0.4330 - accuracy: 0.8243 - val_loss: 0.3963 - val_accuracy: 0.8349
Epoch 4/5
49/49 [==============================] - 55s 1s/step - loss: 0.3671 - accuracy: 0.8458 - val_loss: 0.3771 - val_accuracy: 0.8333
Epoch 5/5
49/49 [==============================] - 53s 1s/step - loss: 0.3412 - accuracy: 0.8573 - val_loss: 0.3494 - val_accuracy: 0.8519


In [21]:
result=model.evaluate(x_test,y_test,verbose=0)
print("Test Accuracy:",result[1])

Test Accuracy: 0.8519200086593628


In [22]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_1 (Embedding)     (None, 10000, 16)         160000    
                                                                 
 flatten_1 (Flatten)         (None, 160000)            0         
                                                                 
 dense_2 (Dense)             (None, 16)                2560016   
                                                                 
 dense_3 (Dense)             (None, 1)                 17        
                                                                 
Total params: 2,720,033
Trainable params: 2,720,033
Non-trainable params: 0
_________________________________________________________________
